package com.example.mounter.ui.login;

import android.app.Activity;

import android.content.Intent;
import android.os.Bundle;

import androidx.appcompat.app.AppCompatActivity;

import android.text.Editable;
import android.text.TextWatcher;
import android.util.Log;
import android.view.View;
import android.view.inputmethod.EditorInfo;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ProgressBar;
import android.widget.Toast;

import com.example.mounter.databinding.ActivityLoginBinding;
import com.example.mounter.ui.ridesearch.RideSearchActivity;
import com.google.firebase.messaging.FirebaseMessaging;

import io.realm.mongodb.User;
import io.realm.mongodb.push.Push;
import io.realm.mongodb.sync.SyncConfiguration;

import static com.example.mounter.Mounter.mounter;
import static com.example.mounter.Mounter.realmPartition;

/* Class autogenerated by Android Studio */
public class LoginActivity extends AppCompatActivity {

    private static final String TAG = "LoginActivity";

    private LoginViewModel loginViewModel;
    private ActivityLoginBinding binding;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Log.i("MyApp", "Successfully started");
        binding = ActivityLoginBinding.inflate(getLayoutInflater());
        setContentView(binding.getRoot());

        loginViewModel = new LoginViewModel();

        final EditText usernameEditText = binding.username;
        final EditText passwordEditText = binding.password;
        final Button loginButton = binding.login;
        final ProgressBar loadingProgressBar = binding.loading;


        // observe the login form
        // display error and disable the "sign in" button if the form is invalid
        loginViewModel.getLoginFormState().observe(this, loginFormState -> {
            if (loginFormState == null) {
                return;
            }
            loginButton.setEnabled(loginFormState.isDataValid());
            if (loginFormState.getUsernameError() != null) {
                usernameEditText.setError(getString(loginFormState.getUsernameError()));
            }
            if (loginFormState.getPasswordError() != null) {
                passwordEditText.setError(getString(loginFormState.getPasswordError()));
            }
        });

        // once the response to the login request is back
        // stop the progress bar animation
        // either proceed to the main activity, or display the error
        loginViewModel.getLoginResult().observe(this, loginResult -> {
            if (loginResult == null) {
                return;
            }
            loadingProgressBar.setVisibility(View.GONE);
            if (loginResult.isFailure()) {
                showLoginFailed(loginResult.getError());
            }
            else {
                configureAppForNewUser();

                setResult(Activity.RESULT_OK);

                //Complete and destroy login activity once successful
                finish();

                Intent intent = new Intent(this, RideSearchActivity.class);

                startActivity(intent);
            }
        });

        TextWatcher afterTextChangedListener = new TextWatcher() {
            @Override
            public void beforeTextChanged(CharSequence s, int start, int count, int after) {
                // ignore
            }

            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {
                // ignore
            }

            @Override
            public void afterTextChanged(Editable s) {
                loginViewModel.loginDataChanged(usernameEditText.getText().toString(),
                        passwordEditText.getText().toString());
            }
        };
        usernameEditText.addTextChangedListener(afterTextChangedListener);
        passwordEditText.addTextChangedListener(afterTextChangedListener);
        passwordEditText.setOnEditorActionListener((v, actionId, event) -> {
            if (actionId == EditorInfo.IME_ACTION_DONE) {
                loginViewModel.login(usernameEditText.getText().toString(),
                        passwordEditText.getText().toString());
            }
            return false;
        });

        loginButton.setOnClickListener(v -> {
            loadingProgressBar.setVisibility(View.VISIBLE);
            loginViewModel.login(usernameEditText.getText().toString(),
                    passwordEditText.getText().toString());
        });
    }

    /**
     * Creates default configuration for Realm based on new user
     * Registers new device in realm so that push notifications can be sent
     */
    private void configureAppForNewUser() {
        User user = mounter.currentUser();
        SyncConfiguration config = new SyncConfiguration.Builder(user, realmPartition)
                .compactOnLaunch()
                .waitForInitialRemoteData()
                .build();

        registerDeviceForPushNotifications();
    }
    /**
     * Registers current device to active user in Realm, <br/>
     * so that push notifications can be sent to this device
     */
    private void registerDeviceForPushNotifications() {
        FirebaseMessaging.getInstance().getToken()
                .addOnCompleteListener(task -> {
                    if (!task.isSuccessful()) {
                        Log.w(TAG, "Fetching FCM registration token failed", task.getException());
                        return;
                    }
                    // Get new FCM registration token
                    String token = task.getResult();

                    Push p = mounter.currentUser().getPush("gcm");
                    p.registerDeviceAsync(token, result -> {
                        Log.d(TAG, "registered device successfully");
                    });
                    Log.d(TAG, "after push");
                });
    }
    private void showLoginFailed(String errorMessage) {
        Toast.makeText(getApplicationContext(), errorMessage, Toast.LENGTH_SHORT).show();
    }
}